"""empty message

Revision ID: 92b55578c815
Revises: 095d445f2275
Create Date: 2018-11-05 08:37:57.854023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b55578c815'
down_revision = '095d445f2275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_loser', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('approved_winner', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('approved_winner')
        batch_op.drop_column('approved_loser')

    # ### end Alembic commands ###
