DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS match;
DROP TABLE IF EXISTS rating;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE match (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  winner_1_id INTEGER NOT NULL,
  winner_2_id INTEGER,
  loser_1_id INTEGER NOT NULL,
  loser_2_id INTEGER,
  winner_score INTEGER NOT NULL,
  loser_score INTEGER NOT NULL,
  played_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (winner_1_id) REFERENCES user (id)
);

CREATE TABLE rating (
  user_id INTEGER NOT NULL,
  match_id INTEGER,
  elo INTEGER NOT NULL,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (match_id) REFERENCES match (id)
);