DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS match;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE match (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  winner_1_id INTEGER NOT NULL,
  winner_2_id INTEGER,
  loser_1_id INTEGER NOT NULL,
  loser_2_id INTEGER,
  played_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (winner_1_id) REFERENCES user (id)
);